server:
  port: 13001

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 暴力关闭eureka的自我保护模式
    enableSelfPreservation: false
spring:
  application:
    name: eurka-server